platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

inputs:
  - name: cf-k8s-networking
  - name: k8s-config-dir
  - name: kubeconfig

run:
  path: cf-k8s-networking-ci/ci/tasks/k8s/kubectl-apply.sh

params:
  KUBECONFIG_CONTEXT:
  # - kubectl k8s context to use from kubeconfig
  FILES_TO_APPLY:
  # - List of k8s yaml files to be applied
  # - Quoted and space-separated
  # - Files will be applied in the order they're listed
  # - Paths are relative to root of the `k8s-config-dir` input

