platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: env-metadata
  - name: cf-k8s-networking-ci

run:
  path: cf-k8s-networking-ci/ci/tasks/scale/pave-cf-for-scale-tests.sh

params:
  GCP_SERVICE_ACCOUNT_KEY:
  CLUSTER_NAME:
  CLOUDSDK_COMPUTE_REGION: "us-west1"
  CLOUDSDK_COMPUTE_ZONE: "us-west1-a"
  GCP_PROJECT: "cf-routing"
