apiVersion: v1
data:
  ccCA: {{.Values.cfroutesync.ccCA}}
  ccBaseURL: {{.Values.cfroutesync.ccBaseURL}}
  uaaCA: {{.Values.cfroutesync.uaaCA}}
  uaaBaseURL: {{.Values.cfroutesync.uaaBaseURL}}
  clientName: {{.Values.cfroutesync.clientName}}
  clientSecret: {{.Values.cfroutesync.clientSecret}}
kind: Secret
metadata:
  name: cfroutesync
  namespace: {{ .Values.system_namespace }}
type: Opaque
