apiVersion: v1
data:
  ccCA: {{.Values.cfroutesync.ccCA}}
  ccBaseURL: {{.Values.cfroutesync.ccBaseURL}}
  uaaCA: {{.Values.cfroutesync.uaaCA}}
  uaaBaseURL: {{.Values.cfroutesync.uaaBaseURL}}
  clientName: {{.Values.cfroutesync.clientName}}
  clientSecret: {{.Values.cfroutesync.clientSecret}}
  {{/* quotes are required to support empty values */}}
  eiriniPodLabelPrefix: "{{.Values.cfroutesync.eiriniPodLabelPrefix}}"
kind: Secret
metadata:
  name: cfroutesync
  namespace: {{ .Values.systemNamespace }}
type: Opaque
