---
platform: linux

image_resource:
  type: docker-image
  source:
     repository: cloudfoundry/capi
     tag: bbl

inputs:
  - name: cf-k8s-networking
  - name: bbl-state

outputs:
  - name: updated-bbl-state

run:
  path: cf-k8s-networking/ci/tasks/bbl/seed-env.sh

params:
  BBL_STATE_DIR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
