platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: cf-k8s-networking
  - name: bbl-state
  - name: release-tarball
    # Input mapping to directory containing .tgz files

run:
  path: cf-k8s-networking/ci/tasks/bosh/upload-release.sh

params:
  BBL_STATE_DIR:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - If unspecified, uses the root of the `bbl-state` input
