---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: cf-k8s-networking
  - name: source1
  - name: source2
    optional: true
  - name: source3
    optional: true
  - name: source4
    optional: true
  - name: source5
    optional: true

outputs:
  - name: merged-bbl-config

params:
  SOURCE1_DIR: ~
  SOURCE2_DIR: ~
  SOURCE3_DIR: ~
  SOURCE4_DIR: ~
  SOURCE5_DIR: ~

run:
  path: cf-k8s-networking/ci/tasks/merge-bbl-config/task.sh
