#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

systemNamespace: cf-system
workloadsNamespace: cf-workloads

cfroutesync:
  image: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:466cc0ec65b02a37684ef48e4d41df4cfcd0f27bd5cb209c8ddd13abbde774f0

  ccCA: 'base64_encoded_cloud_controller_ca'
  ccBaseURL: 'https://api.example.com'
  uaaCA: 'base64_encoded_uaa_ca'
  uaaBaseURL: 'https://uaa.example.com'
  clientName: 'uaaClientName'
  clientSecret: 'base64_encoded_uaaClientSecret'

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:a9e67c2fc83e2a8f65f378f8538858463a7a8a03b37c6a019bf0a966dafe89dd

service:
  externalPort: 80
