#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

istioVersion: 1.6.4
systemNamespace: cf-system
workloadsNamespace: cf-workloads

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:59bae5250aac171014bac055ef510f5818660d2fab70133618c83c514b12a577
upgradeSidecars:
  image: gcr.io/cf-networking-images/cf-k8s-networking/upgrade-sidecars@sha256:17d0678672da67f1c43b43013766649b363f06ebfbea4643409bdc1b16fa42bb

service:
  externalPort: 80
