#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-certs
  namespace: cf-system
type: Opaque
stringData:
  tls.crt: #@ data.values.backendTlsCert
  tls.key: #@ data.values.backendTlsKey

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cf-system
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-certs
              mountPath: /etc/nginx-certs
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-certs
          secret:
            secretName: nginx-certs
        - name: nginx-config
          configMap:
            name: nginx-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cf-system
data:
  nginx.conf: #@ data.values.nginxConfig

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cf-system
spec:
  ports:
    - name: https
      port: 443
  selector:
    app: nginx

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-route-for-nginx
  namespace: cf-system
spec:
  gateways:
    - wildcard-sys-gateway
  hosts:
    - #@ data.values.systemComponentExternalAddress
  http:
    - route:
        - destination:
            host: nginx.cf-system.svc.cluster.local

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-destination
  namespace: istio-system
spec:
  host: nginx.cf-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca.crt
  exportTo:
    - "."
