---
apiVersion: indicatorprotocol.io/v1
kind: IndicatorDocument
metadata:
  labels:
    deployment: cf

spec:
  product:
    name: cf-k8s-networking
    version: NA

  indicators:
    - name: cpu_usage_percent
      promql: rate(container_cpu_usage_seconds_total{job="kubernetes-cadvisor",pod_name=~"istio-ingressgateway-.*",container_name="istio-proxy"}[1m]) * 100
      documentation:
        title: CPU by ingressgateway pod
        description: |
          Percentage CPU utilization of the Istio IngressGateway pods. This measurement is not normalized.
          When this metric is at 100%, it means that 100% of 1vCPU of the node is being utilized. 200% means two vCPUS of the node are under heavy load, etc.

          **Use**: Consistently elevated CPU utilization (close to pod limits) indicates that the platform is receiving heavy traffic and the ingressgateways
          should be scaled horizontally.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
    - name: container_memory_working_set_megabytes
      promql: container_memory_working_set_bytes{job="kubernetes-cadvisor",pod_name=~"istio-ingressgateway-.*",container_name="istio-proxy"} / 1024 / 1024
      documentation:
        title: Memory Usage by ingressgateway pod
        description: |
          Amount of working set memory (in megabytes) used by the istio-proxy (envoy) container running on the IngressGateway pods.
          Kubernetes uses this metric to make Pod eviction decisions when node memory resources are low.

          This metric is derived from the memory cgroup's reported `usage_in_bytes` of the container - its reported `inactive_file` bytes (the amount of inactive file-based memory).

          **Use**: Unbounded growth of this metric over time could indicate a potential memory leak.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
    - name: cfroutesync_last_updated_at
        promql: idelta(cfroutesync_last_updated_at[1m])
        documentation:
          title: Seconds since last update to cfroutesync
          description: |
            Time in seconds since the last successful time fetching information from Cloud Controller.

            **Use**: When this number grows significantly and consistently over 10s, cfroutesync is having trouble successfully getting information from Cloud Controller.
          recommendedMeasurement: |
            TBD
          recommendedResponse: |
            TBD
    - name: cfroutesync_fetched_routes
        promql: cfroutesync_fetched_routes
        documentation:
          title: Number of routes
          description: |
            Number of routes cfroutesync has fetched from Cloud Controller

            **Use**: When this is not updated according to the number of routes expected, the control plane is unhealthy.
          recommendedMeasurement: |
            TBD
          recommendedResponse: |
            TBD
    - name: http_req_per_second
      promql: sum(rate(istio_cf_requests_total{destination_workload_namespace="cf-workloads"}[1m])) by (source_name)
      documentation:
        title: Requests per second by ingressgateway pod
        description: |
          Number of HTTP requests per second going through the Istio IngressGateways to apps, averaged over 1 minute.
          This number is reported for each Istio IngressGateway pod.

          **Use**: When this metric is high, indicates that the platform is receiving heavy traffic.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
    - name: envoy_update_failures
      promql: rate(envoy_cluster_manager_cds_update_failure{app="istio-ingressgateway"}[1m])
      documentation:
        title: Envoy Update Failure Rate
        description: |
          Envoy CDS update failures can indicate that Envoy isn't receiving updates from Istio control plane. This means
          it may not be aware of recently mapped/unmapped routes.

          **Use**: When this metric is above 0 for extended periods of time this may indicate that the Envoy is not
          receiving configuration updates.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
