---
apiVersion: indicatorprotocol.io/v1
kind: IndicatorDocument
metadata:
  labels:
    deployment: cf

spec:
  product:
    name: cf-k8s-networking
    version: NA

  indicators:
    - name: cpu_usage_percent
      promql: rate(container_cpu_usage_seconds_total{job="kubernetes-cadvisor",pod_name=~"istio-ingressgateway-.*",container_name="istio-proxy"}[1m]) * 100
      documentation:
        title: CPU by ingressgateway pod
        description: |
          Percentage CPU utilization of the Istio IngressGateway pods. This measurement is not normalized.
          When this metric is at 100%, it means that 100% of 1vCPU of the node is being utilized. 200% means two vCPUS of the node are under heavy load, etc.

          **Use**: Consistently elevated CPU utilization (close to pod limits) indicates that the platform is receiving heavy traffic and the ingressgateways
          should be scaled horizontally.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
    - name: container_memory_working_set_bytes
      promql: container_memory_working_set_bytes{job="kubernetes-cadvisor",pod_name=~"istio-ingressgateway-.*",container_name="istio-proxy"}
      documentation:
        title: Memory Usage by ingressgateway pod
        description: |
          Amount of working set memory (in bytes) used by the istio-proxy (envoy) container running on the IngressGateway pods.
          Kubernetes uses this metric to make Pod eviction decisions when node memory resources are low.

          This metric is derived from the memory cgroup's reported `usage_in_bytes` of the container - its reported `inactive_file` bytes (the amount of inactive file-based memory).

          **Use**: Unbounded growth of this metric over time could indicate a potential memory leak.
        recommendedMeasurement: |
          TBD
        recommendedResponse: |
          TBD
