---

resources:

- name: weekly-sunday
  type: time
  source:
    location: America/Los_Angeles
    start: 23:00
    stop: 23:30
    days: [Sunday]

- name: cf-k8s-networking
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git

- name: networking-oss-deployments
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: bosh-deployment
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/bosh-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v*

jobs:
- name: eirini-dev-1-bbl-up
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: cf-deployment-concourse-tasks
          resource: cf-deployment-concourse-tasks
        - get: cf-k8s-networking
        - get: networking-oss-deployments
        - get: bosh-deployment
        - get: weekly-sunday
          trigger: true
    - task: seed-bbl-env
      file: cf-k8s-networking/ci/tasks/seed-env/task.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
        DOMAIN: &eirini-dev-1-domain "eirini-dev-1.routing.cf-app.com"
    - put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true
    - task: collect-ops-files
      file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
      input_mapping:
        base-ops-files: bosh-deployment
        new-ops-files: cf-k8s-networking
    - task: bbl-up-eirini-dev-1
      file: cf-deployment-concourse-tasks/bbl-up/task.yml
      input_mapping:
        bbl-state: updated-bbl-state
        bbl-config: updated-bbl-state
      params: &bbl-up-eirini-dev-1-params
        BBL_STATE_DIR: "environments/eirini-dev-1"
        BBL_IAAS: "gcp"
        BBL_LB_CERT: "certs/load-balancer/server.crt"
        BBL_LB_KEY: "certs/load-balancer/server.key"
        LB_DOMAIN: *eirini-dev-1-domain
        BBL_ENV_NAME: "eirini-dev-1"
        BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        BBL_GCP_REGION: us-west1
      ensure:
        put: networking-oss-deployments
        params:
          repository: updated-bbl-state
          rebase: true
