resources:
  - name: k8s-deploy-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy
      username: _json_key
      password: ((shared_gcp_account_creds))

  - name: cf-k8s-networking
    type: git
    icon: github-box
    source:
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: cf-k8s-networking-ci
    type: git
    icon: github-box
    source:
      branch: develop
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci

  - name: cf-k8s-networking-docker-images
    type: git
    icon: github-box
    source:
      branch: develop
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci/dockerfiles

  - name: kind-integration-test-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-networking-images/cf-k8s-networking/kind-integration-test-env
      username: _json_key
      password: ((gcp_gcr_service_account_key))

  - name: upgrade-sidecars-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-networking-images/cf-k8s-networking/upgrade-sidecars
      username: _json_key
      password: ((gcp_gcr_service_account_key))

  - name: httpbin-repo
    type: git
    icon: github-box
    source:
      uri: git@github.com:cf-routing/httpbin.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: httpbin-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/httpbin
      username: ((dockerhub_public.username))
      password: ((dockerhub_public.password))

  - name: proxy-repo
    type: git
    icon: github-box
    source:
      uri: git@github.com:cf-routing/proxy.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: proxy-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/proxy
      username: ((dockerhub_public.username))
      password: ((dockerhub_public.password))

jobs:
  - name: build-k8s-deploy-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - put: k8s-deploy-image
        params:
          build: cf-k8s-networking-docker-images/ci/dockerfiles/deploy
          tag_as_latest: true

  - name: build-kind-integration-test-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - put: kind-integration-test-image
        params:
          build: cf-k8s-networking-docker-images/ci/dockerfiles/test
          tag_as_latest: true

  - name: build-httpbin-image
    plan:
      - get: httpbin-repo
        trigger: true
      - put: httpbin-image
        params:
          build: httpbin-repo
          tag_as_latest: true

  - name: build-proxy-image
    plan:
      - get: proxy-repo
        trigger: true
      - put: proxy-image
        params:
          build: proxy-repo
          tag_as_latest: true

  - name: build-upgrade-sidecars-job-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - in_parallel:
          # Note: 'initial-image' is not the image we publish. Just needed as intermediate
          # step to inspect so we can label the final image.
          - put: initial-image
            resource: upgrade-sidecars-image
            params:
              build: cf-k8s-networking-docker-images/ci/dockerfiles/upgrade
              # dockerfile: cf-k8s-networking/routecontroller/Dockerfile
            get_params:
              save: true
          - task: build-tag-file
            file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
      - task: build-image-labels
        file: cf-k8s-networking-ci/ci/tasks/docker/build-image-labels.yml
      - put: upgrade-sidecars-image
        params:
          build: cf-k8s-networking-docker-images/ci/dockerfiles/upgrade
          # dockerfile: cf-k8s-networking/routecontroller/Dockerfile
          additional_tags: docker-info/tags
          tag_as_latest: true
          labels_file: labels/labels.json
      - task: add-updated-digest
        file: cf-k8s-networking-ci/ci/tasks/docker/add-updated-digest.yml
        input_mapping:
          image-resource: upgrade-sidecars-image
        params:
          COMPONENT_NAME: upgrade-sidecars
      - put: cf-k8s-networking
        params:
          repository: cf-k8s-networking-modified
          rebase: true

