resources:
  - name: cfroutesync
    type: git
    icon: github-box
    source:
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: master
      paths:
        - cfroutesync

  - name: cf-k8s-networking-mod
    type: git
    icon: github-box
    source:
      branch: master
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - cfroutesync/go.mod
        - cfroutesync/go.sum
        - cfroutesync/integration/Dockerfile

  - name: k8s-deploy-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy
      username: _json_key
      password: ((shared_gcp_account_creds))

  - name: cf-k8s-networking
    type: git
    icon: github-box
    source:
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: master
      private_key: ((github_private_key.private_key))

  - name: cf-k8s-networking-ci
    type: git
    icon: github-box
    source:
      branch: master
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci
  - name: cfroutesync-integration-test-env-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-networking-images/cfroutesync-integration-test-env
      username: _json_key
      password: ((gcp_gcr_service_account_key))

#  - name: every-week
#    type: time
#    source:
#      location: America/Tijuana
#      start: 12:00 PM
#      stop: 1:00 PM
#      days: [Monday]

jobs:
  - name: build-k8s-deploy-image
    plan:
      - in_parallel:
#          - get: every-week
#            trigger: true
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cfroutesync
            trigger: true
      - put: k8s-deploy-image
        params:
          build: cf-k8s-networking/ci/dockerfiles/deploy
          tag_as_latest: true
      - task: add-updated-sha
        file: cf-k8s-networking-ci/ci/tasks/docker/add-updated-sha.yml
      - put: cf-k8s-networking
        params:
          repository: cf-k8s-networking-modified

  - name: build-integration-test-env-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking-mod
            trigger: true
          - get: cf-k8s-networking-ci
      - task: build-tag-file
        file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
        input_mapping:
          cf-k8s-networking: cf-k8s-networking-mod
      - put: cfroutesync-integration-test-env-image
        params:
          build: cf-k8s-networking-mod/cfroutesync
          dockerfile: cf-k8s-networking-mod/cfroutesync/integration/Dockerfile
          additional_tags: docker-info/tags
          tag_as_latest: true