resources:
  - name: k8s-deploy-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy
      username: _json_key
      password: ((shared_gcp_account_creds))

  - name: cf-k8s-networking
    type: git
    icon: github-box
    source:
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: cf-k8s-networking-ci
    type: git
    icon: github-box
    source:
      branch: develop
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci

  - name: cf-k8s-networking-docker-images
    type: git
    icon: github-box
    source:
      branch: develop
      private_key: ((github_private_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci/dockerfiles

  - name: kind-integration-test-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/cf-networking-images/cf-k8s-networking/kind-integration-test-env
      username: _json_key
      password: ((gcp_gcr_networking_images_service_account_key))

  - name: upgrade-sidecars-image
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/cf-networking-images/cf-k8s-networking/upgrade-sidecars
      username: _json_key
      password: ((gcp_gcr_networking_images_service_account_key))

  - name: httpbin-repo
    type: git
    icon: github-box
    source:
      uri: git@github.com:cf-routing/httpbin.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: httpbin-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/httpbin
      username: ((dockerhub_public.username))
      password: ((dockerhub_public.password))

  - name: proxy-repo
    type: git
    icon: github-box
    source:
      uri: git@github.com:cf-routing/proxy.git
      branch: develop
      private_key: ((github_private_key.private_key))

  - name: proxy-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/proxy
      username: ((dockerhub_public.username))
      password: ((dockerhub_public.password))

jobs:
  - name: build-k8s-deploy-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - put: k8s-deploy-image
        params:
          build: cf-k8s-networking-docker-images/ci/dockerfiles/deploy
          tag_as_latest: true

  - name: build-kind-integration-test-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - put: kind-integration-test-image
        params:
          build: cf-k8s-networking-docker-images/ci/dockerfiles/test
          tag_as_latest: true

  - name: build-httpbin-image
    plan:
      - get: httpbin-repo
        trigger: true
      - put: httpbin-image
        params:
          build: httpbin-repo
          tag_as_latest: true

  - name: build-proxy-image
    plan:
      - get: proxy-repo
        trigger: true
      - put: proxy-image
        params:
          build: proxy-repo
          tag_as_latest: true

  - name: build-upgrade-sidecars-job-image
    plan:
      - in_parallel:
          - get: cf-k8s-networking
          - get: cf-k8s-networking-ci
          - get: cf-k8s-networking-docker-images
            trigger: true
      - in_parallel:
          - task: build-upgrade-sidecars-job-image
            privileged: true
            file: cf-k8s-networking-ci/ci/tasks/docker/build-oci-image.yml
            input_mapping:
              repository: cf-k8s-networking-docker-images
            output_mapping:
              image: upgrade-sidecars-image
            params:
              CONTEXT: ci/dockerfiles/upgrade
              DOCKERFILE: ci/dockerfiles/upgrade/Dockerfile
          - task: build-tag-file
            file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
      - task: annotate
        file: cf-k8s-networking-ci/ci/tasks/docker/annotate.yml
        input_mapping:
          input-image: upgrade-sidecars-image
          repository: cf-k8s-networking
        output_mapping:
          output-image: upgrade-sidecars-annotated-image
      - put: upgrade-sidecars-image
        params:
          image: upgrade-sidecars-annotated-image/image.tar
          additional_tags: docker-info/tags
      - task: add-updated-digest
        file: cf-k8s-networking-ci/ci/tasks/docker/add-updated-digest.yml
        input_mapping:
          image-resource: upgrade-sidecars-image
        params:
          COMPONENT_NAME: upgrade-sidecars
      - put: cf-k8s-networking
        params:
          repository: cf-k8s-networking-modified
          rebase: true

