---
resources:
- name: istio-release
  type: github-release
  icon: github-box
  source:
    owner: istio
    repository: istio
    version: latest
    access_token: ((github_access_token))

- name: istio
  type: git
  icon: github-box
  source:
    uri: https://github.com/istio/istio.git
    fetch_tags: true

- name: istio-proxyv2-image
  type: registry-image
  source:
    repository: docker.io/istio/proxyv2

- name: cf-networking-proxyv2-image
  type: registry-image
  source:
    repository: gcr.io/cf-routing/proxyv2
    username: _json_key
    password: ((shared_gcp_account_creds))

- name: istio-pilot-image
  type: registry-image
  source:
    repository: docker.io/istio/pilot

- name: cf-networking-pilot-image
  type: registry-image
  source:
    repository: gcr.io/cf-routing/pilot
    username: _json_key
    password: ((shared_gcp_account_creds))

- name: cf-k8s-networking-ci
  type: git
  icon: github-box
  source:
    branch: develop
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    paths:
      - ci
      - config

jobs:
- name: pull-and-tag-istio-images
  plan:
  - in_parallel:
    - get: cf-k8s-networking-ci
    - get: istio-release
      trigger: true
    - get: istio
    - get: istio-proxyv2-image
      resource: istio-proxyv2-image
      params:
        format: oci
    - get: istio-pilot-image
      resource: istio-pilot-image
      params:
        format: oci
  - task: prepare-repo
    # NOTE(ck,lh): Our goal is to have the Istio repo at the same commit the
    # release was created at. Normally, we would use the git concourse
    # resource; the git resource clones a single branch from a git repo.
    # However, Istio creates branches for its releases. If we use the git
    # resource to pull master, we may not have the release commit. If we use
    # the git resource to pull the current release branch, then we will need to
    # manually update this pipeline. In order to avoid missing commits and
    # manual updates, we are using a task instead. We are simply cloning the
    # repository manually in this task, and then passing it on as an output.
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: c2cnetworking/small-git
      inputs:
      - name: istio-release
      outputs:
      - name: istio-at-specified-sha
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          git clone https://github.com/istio/istio.git ./istio-at-specified-sha
          pushd istio-at-specified-sha > /dev/null
            git checkout "$(cat ../istio-release/commit_sha)"
            git status
          popd
  - task: annotate-istio-proxyv2
    file: cf-k8s-networking-ci/ci/tasks/docker/annotate.yml
    input_mapping:
      input-image: istio-proxyv2-image
      repository: istio-at-specified-sha
    output_mapping:
      output-image: istio-proxyv2-annotated-image
  - task: annotate-istio-pilot
    file: cf-k8s-networking-ci/ci/tasks/docker/annotate.yml
    input_mapping:
      input-image: istio-pilot-image
      repository: istio-at-specified-sha
    output_mapping:
      output-image: istio-pilot-annotated-image
  - in_parallel:
    - put: cf-networking-pilot-image
      params:
        image: istio-pilot-annotated-image/image.tar
        additional_tags: istio-release/tag
    - put: cf-networking-proxyv2-image
      params:
        image: istio-proxyv2-annotated-image/image.tar
        additional_tags: istio-release/tag
