apiVersion: "apps.cloudfoundry.org/v1alpha1"
kind: RouteBulkSync
metadata:
  name: example-route-bulk-sync
  namespace: cf-workloads
spec:
  selector:
    matchLabels:
      cloudfoundry.org/route-bulk-sync: "true"
  template:
    metadata:
      labels:
        cloudfoundry.org/route-bulk-sync: "true"
