platform: linux

image_resource:
  type: registry-image
  source:
      # Deplab is a tool to annotate Docker images with additional metadata, such
      # as SHA of the source code used to build an image, the list of used packages
      # in the image, etc.
      repository: dev.registry.pivotal.io/navcon/deplab-task
      tag: dev
      username: pivotal-cf-networking@pivotal.io
      password: ((pivotal_cf_networking_pivnet_password))

inputs:
  # When using this task, you must specify EITHER input-image-tar OR input-image-name
  # input-image-tar should contain an image.tar file
  - name: input-image-tar
    optional: true
  # input-image-name should contain a name.txt file with the name of the image
  - name: input-image-name
    optional: true
  # repository is the git respository containing the source code for the image
  - name: repository
  - name: cf-k8s-networking-ci

outputs:
  # output-image will contain a new annotated image under image.tar
  - name: output-image

run:
  path: cf-k8s-networking-ci/ci/tasks/docker/annotate.sh
