#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cfroutesync
  namespace: #@ data.values.systemNamespace
type: Opaque
data:
  clientSecret: #@ data.values.cfroutesync.clientSecret
