platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

inputs:
  - name: cf-k8s-networking-ci

outputs:
  - name: kubeconfig

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/generate-kube-config.sh

params:
  GCP_SERVICE_ACCOUNT_KEY:
  CLUSTER_NAME:
  CLOUDSDK_COMPUTE_REGION: "us-west1"
  CLOUDSDK_COMPUTE_ZONE: "us-west1-a"
  GCP_PROJECT: "cf-routing"
