platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking-ci
  - name: env-metadata

outputs:
  - name: integration-config

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/generate-integration-config.sh
