---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: cf-k8s-networking
  - name: cloud-config
  - name: bbl-state

run:
  path: cf-k8s-networking/ci/tasks/update-cloud-config/task.sh

params:
  BBL_STATE_DIR:
  CLOUD_CONFIG_PATH:
