name: Tests
on: [push]
jobs:
  build:

    name: CF Route Syncer
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cf-routing/cf-k8s-networking/cfroutesync-integration-test-env

    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v1

    - name: Run tests
      working-directory: cfroutesync
      run: bin/test local
